
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle # Cache for gems
      - node_modules:/app/node_modules # Cache for node_modules
    environment:
      RAILS_ENV: development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.message_me.rule=Host(`message.thinhnw.site`)"  # Replace with your domain
      - "traefik.http.routers.message_me.entrypoints=websecure"
      - "traefik.http.routers.message_me.tls=true"
      - "traefik.http.routers.message_me.tls.certresolver=myresolver"
      - "traefik.http.services.message_me.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_traefik"
    networks:
      - traefik_traefik

networks:
  traefik_traefik:
    external: true

volumes:
  bundle_cache:
  node_modules: